config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :budgets do
    resources :accounts
  end

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :budget

  validates :name, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
# frozen_string_literal: true

class Budget < ApplicationRecord
  has_many :accounts, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable, :confirmable,
         :lockable

  has_many :budgets
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :set_budget
  before_action :set_account, only: %i[show edit update destroy]
  before_action :authorize_model

  # GET /budgets/:budget_id/accounts/1 or /budgets/:budget_id/accounts/1.json
  def show; end

  # GET /budgets/:budget_id/accounts/new
  def new
    @account = @budget.accounts.build
  end

  # GET /budgets/:budget_id/accounts/1/edit
  def edit; end

  # POST /budgets/:budget_id/accounts or /budgets/:budget_id/accounts.json
  def create
    @account = @budget.accounts.create(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to budget_url(@budget), notice: t('.success') }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/:budget_id/accounts/1 or /budgets/:budget_id/accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to budget_account_url(@budget, @account), notice: t('.success') }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/:budget_id/accounts/1 or /budgets/:budget_id/accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to budget_url(@budget), notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private

  def set_budget
    @budget = Budget.find(params[:budget_id])
  end

  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:name, :credit)
  end

  def authorize_model
    authorize @account || Account
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
  after_action :verify_authorized

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = I18n.t('not_authorized')
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/budgets_controller.rb
# frozen_string_literal: true

class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[show edit update destroy]
  before_action :authorize_model

  # GET /budgets or /budgets.json
  def index
    @budgets = policy_scope Budget
  end

  # GET /budgets/1 or /budgets/1.json
  def show; end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit; end

  # POST /budgets or /budgets.json
  def create
    @budget = current_user.budgets.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budget_url(@budget), notice: t('.success') }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: t('.success') }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private

  def budget_params
    params.require(:budget).permit(:name)
  end

  def set_budget
    @budget = policy_scope(Budget).find(params[:id])
  end

  def authorize_model
    logger.error "foo bar"
    logger.error @budget
    authorize @budget || Budget
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_after_action :verify_authorized, only: :index

  def index; end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/budgets_helper.rb
# frozen_string_literal: true

module BudgetsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: [@budget, account]) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :credit, style: "display: block" %>
    <%= form.number_field :credit %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", budget_account_path(@budget, @account) %> |
  <%= link_to "Back to budget", budget_path(@budget) %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to budget", budget_path(@budget) %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @account.name %></h1>

<div>
  <%= link_to "Edit this account", edit_budget_account_path(@budget, @account) %> |
  <%= link_to "Back to #{@budget.name}", budget_path(@budget) %>

  <%= button_to "Destroy this account", [@budget, @account], method: :delete %>
</div>

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
  <p>
    <strong>Name:</strong>
    <%= budget.name %>
  </p>

</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgets</h1>

<div id="budgets" class="list-group">
  <% @budgets.each do |budget| %>
    <%= link_to budget.name, budget, class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

<p class="mt-4">
<%= link_to new_budget_path, class: 'btn btn-primary' do %>
  New Budget
<% end %>
</p>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @budget.name %></h1>

<h2>Accounts</h2>

<div id="accounts" class="list-group">
  <% @budget.accounts.each do |account| %>
    <%= link_to account.name, [@budget, account], class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

<p class="mt-4">
  <%= link_to new_budget_account_path(@budget), class: 'btn btn-primary' do %>
    New Account
  <% end %>
</p>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>

app/views/home/index.html.erb
Hi!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Fixed navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <main class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>